name: "ðŸ“š Blog Updater"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */24 * * *' # Runs Every 24 Hours

jobs:
  update_blogs:
    name: "Update Blogs"
    runs-on: ubuntu-latest
    steps:
      - name: "ðŸ“¥  Fetching Repository Contents"
        uses: actions/checkout@main

      - name: "ðŸ“š  Hashnode Updater"
        uses: "varunsridharan/action-hashnode-blog@1.2"
        with:
          USERNAME: 'Pradumnasaraf' # Hashnode Username
          COUNT: 2 # MAX Visisble
          STYLE: "blog-left"
          BLOG_URL: "https://blog.pradumnasaraf.dev"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
